# Generated by Django 3.2.5 on 2023-04-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auhor',
            new_name='author',
        ),
    ]
